apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/certificate-pocket-id-database-server.yaml
- resources/certificate-pocket-id-database-client.yaml
- resources/certificate-pocket-id-server.yaml
