apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  chart: istiod
  version: "1.29.x"
  sourceRef:
    kind: HelmRepository
    name: istio
  interval: 24h
  reconcileStrategy: ChartVersion
