apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resources/server-tls-certificate.yaml
- resources/certificate-openbao-database-client.yaml
- resources/certificate-openbao-database-server.yaml
