apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-server-secretkey
  namespace: authentik
spec:
  refreshPolicy: CreatedOnce
  target:
    name: authentik-server-secretkey
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        secret-key: "{{ .password | toString }}" # password is the property in the generator output
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: authentik-server-secretkey
