apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-server-secretkey-creation
  namespace: authentik
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "get"
  - "list"
