apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pocketid-server-encryptionkey-creation
  namespace: pocket-id
subjects:
- kind: ServiceAccount
  name: default
  namespace: pocket-id
roleRef:
  kind: Role
  name: pocketid-server-encryptionkey-creation
  apiGroup: rbac.authorization.k8s.io
