# nginx gateway fabric only supports 1 gateway class as of 13 may 2026 and the default one is called 'nginx'.
# the helm chart installs the gateway class for us.
# i've renamed the gateway class to 'ngf' in the helm chart values.
