apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/namespace.yaml
- resources/certificate.yaml
- resources/nginxproxy.yaml
- resources/gateway.yaml
- resources/httproute.yaml
