apiVersion: v1
kind: ConfigMap
metadata:
  name: pocket-id
  namespace: pocket-id
data:
  APP_URL: "https://auth.hunt.internal"
  INTERNAL_APP_URL: "https://pocket-id-server.pocket-id.svc.cluster.local"
  ENCRYPTION_KEY_FILE: "/app/secrets/encryption-key" # value will be output of: openssl rand -base64 32
  TLS_CERT_FILE: "/app/secrets/tls.crt"
  TLS_KEY_FILE: "/app/secrets/tls.key"
  DB_CONNECTION_STRING: "postgres://app@pocket-id-db-rw.pocket-id.svc.cluster.local:5432/app?sslmode=verify-full&sslrootcert=/app/secrets/ca.crt&sslcert=/app/secrets/tls.crt&sslkey=/app/secrets/tls.key"
  FILE_BACKEND: "database"
  TRUSTED_PLATFORM: "X-Forwarded-For"
  PUID: "1000"
  PGID: "1000"
  HOST: "0.0.0.0"
  PORT: "1411"
  LOG_LEVEL: "info"
  LOG_JSON: "true"
  VERSION_CHECK_DISABLED: "true"
  ANALYTICS_DISABLED: "true"
#  OTEL_TRACES_EXPORTER: otlp
#  OTEL_METRICS_EXPORTER: otlp
#  OTEL_LOGS_EXPORTER: otlp
#  OTEL_EXPORTER_OTLP_ENDPOINT: ""
#  OTEL_METRICS_EXPORTER: prometheus
#  OTEL_EXPORTER_PROMETHEUS_HOST: ""
#  OTEL_EXPORTER_PROMETHEUS_PORT: ""
