---
apiVersion: v1
kind: Service
metadata:
  name: pocket-id-server
  namespace: pocket-id
spec:
  ports:
    - port: 443
      targetPort: 1411
      protocol: TCP
  ipFamilies:
  - "IPv4"
  selector:
    app: pocket-id
...
---
apiVersion: v1
kind: Service
metadata:
  name: pocket-id-server-headless
  namespace: pocket-id
spec:
  clusterIP: None
  ports:
    - port: 443
      targetPort: 1411
      protocol: TCP
  selector:
    app: pocket-id
...
