apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: long-complex-password
  namespace: openbao
spec:
  length: 64 # dont set this higher since openbao's bcrypt only supports a max of 72 bytes
  noUpper: false
  allowRepeat: true
  # symbolCharacters: defaults to ~!@#$%^&*()_+`-={}|[]\:"<>?,./
  # digits: number defaults to 25 percent of the length
  # symbols: number defaults to 25 percent of the length
  # encoding: default is raw
