apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-corefile
  namespace: coredns
data: # the capital C is intentional
  Corefile: |
    lab.hunt.internal {
      forward . 192.168.30.3
      errors
      loadbalance
      log
      loop
      ready
      reload
    }
    testing.hunt.internal {
      forward . 192.168.30.4
      errors
      loadbalance
      log
      loop
      ready
      reload
    }
    home.hunt.internal {
      file /etc/coredns/zone/home.hunt.internal {
        reload 60s
        reload_by_mtime
      }
      errors
      loadbalance
      log
      loop
      ready
      reload
      health {
        lameduck 5s
      }
    }
    . {
      forward . https://1.1.1.1 https://1.0.0.1 {
        tls_servername cloudflare-dns.com
      }
      errors
      loadbalance
      log
      loop
      ready
      reload
      cache 300
    }
