---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxoperator-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/fluxoperator/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/install/overlays/lab
...
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: <>
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: <>
#     namespace: flux-system
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 10m
#   timeout: 5m
#   prune: true
#   wait: true
#   path: <>
# ...
