apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/gitrepository.yaml
- resources/kustomization.yaml

# https://docs.nginx.com/nginx-gateway-fabric/overview/gateway-api-compatibility/
