apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart: authentik
  version: "2026.5.x"
  sourceRef:
    kind: HelmRepository
    name: authentik
  interval: 24h
  reconcileStrategy: ChartVersion
