apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/namespace.yaml
- resources/password-openbao-account.yaml # this is an eso password generator
- resources/externalsecret.yaml
- resources/role.yaml
- resources/rolebinding.yaml
- resources/job-openbao-server-unsealkey-createprevious.yaml
- resources/job-openbao-server-unsealkey-createcurrent.yaml
