---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxoperator-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/fluxoperator/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxoperator-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: fluxoperator-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/fluxoperator/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginxgatewayfabric-preinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: fluxoperator-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginxgatewayfabric/preinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-install
  namespace: flux-system
spec:
  dependsOn:
  - name: fluxoperator-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/certmanager/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/longhorn/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginxgatewayfabric-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  - name: nginxgatewayfabric-preinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginxgatewayfabric/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/coredns/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/istio/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externalsecretsoperator-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/externalsecretsoperator/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnativepg-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cloudnativepg/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-postinstall1
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/postinstall1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trustmanager-install
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/trustmanager/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-postinstall1
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/certmanager/postinstall1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-postinstall2
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-postinstall1
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/certmanager/postinstall2/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/istio/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginxgatewayfabric-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-postinstall1
    namespace: flux-system
  - name: nginxgatewayfabric-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginxgatewayfabric/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trustmanager-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-postinstall2
    namespace: flux-system
  - name: trustmanager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/trustmanager/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: coredns-install
    namespace: flux-system
  - name: nginxgatewayfabric-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/coredns/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-postinstall2
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  - name: nginxgatewayfabric-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/postinstall2/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: longhorn-install
    namespace: flux-system
  - name: nginxgatewayfabric-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/longhorn/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-preinstall1
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-postinstall1
    namespace: flux-system
  - name: externalsecretsoperator-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/preinstall1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-preinstall2
  namespace: flux-system
spec:
  dependsOn:
  - name: openbao-preinstall1
    namespace: flux-system
  - name: cloudnativepg-install
    namespace: flux-system
  - name: longhorn-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/preinstall2/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-install
  namespace: flux-system
spec:
  dependsOn:
  - name: openbao-preinstall2
    namespace: flux-system
  - name: trustmanager-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: openbao-install
    namespace: flux-system
  - name: nginxgatewayfabric-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: externalsecretsoperator-postinstall
  namespace: flux-system
spec:
  dependsOn:
  - name: externalsecretsoperator-install
    namespace: flux-system
  - name: openbao-install
    namespace: flux-system
  - name: trustmanager-postinstall
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/externalsecretsoperator/postinstall/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-preinstall1
  namespace: flux-system
spec:
  dependsOn:
  - name: certmanager-postinstall1
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/pocketid/preinstall1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocketid-preinstall2
  namespace: flux-system
spec:
  dependsOn:
  - name: pocketid-preinstall1
    namespace: flux-system
  - name: cloudnativepg-install
    namespace: flux-system
  - name: longhorn-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: false # flux doesn't know how to monitor a cnpg cluster file correctly by default. trying manual health check definition.
  healthchecks:
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    name: pocketid-db
    namespace: pocket-id
  path: manifests/pocketid/preinstall2/overlays/lab
...
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: pocketid-install
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: pocketid-preinstall2
#     namespace: flux-system
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 10m
#   timeout: 5m
#   prune: true
#   wait: true
#   path: manifests/pocketid/install/overlays/lab
# ...
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: pocketid-postinstall
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: pocketid-install
#     namespace: flux-system
#   - name: nginxgatewayfabric-postinstall
#     namespace: flux-system
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 10m
#   timeout: 5m
#   prune: true
#   wait: true
#   path: manifests/pocketid/postinstall/overlays/lab
# ...
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: <>
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: <>
#     namespace: flux-system
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 10m
#   timeout: 5m
#   prune: true
#   wait: true
#   path: <>
# ...
