apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-corefile
  namespace: coredns
data: # the capital C is intentional
  Corefile: |
    lab.hunt.internal:53 {
      file /etc/coredns/zone/lab.hunt.internal {
        reload 60s
        reload_by_mtime
      }
      errors
      health :8080 {
        lameduck 5s
      }
      loadbalance
      log
      ready :8081
      reload
    }
