apiVersion: v1
kind: Service
metadata:
  name: pocketid-server-headless
  namespace: pocket-id
spec:
  clusterIP: None
  ports:
    - port: 443
      targetPort: 1411
      protocol: TCP
  selector:
    app: pocketid
