apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openbao-db
  namespace: openbao
spec:
  instances: 3
  certificates:
    serverCASecret: openbao-db-tls-server
    serverTLSSecret: openbao-db-tls-server
    clientCASecret: openbao-db-tls-server
    replicationTLSSecret: openbao-db-tls-replication
  postgresql:
    pg_hba:
    - hostssl app all all cert
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: 5Gi
      storageClassName: withoutreplication
      volumeMode: Filesystem
  logLevel: info
