apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginxgatewayfabric
  namespace: nginx-gateway-fabric
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Create
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: nginxgatewayfabric
  targetNamespace: nginx-gateway-fabric
  chartRef:
    kind: OCIRepository
    name: nginxgatewayfabric
    namespace: nginx-gateway-fabric
  values:
    nginxGateway:
      config:
        logging:
          level: info
      productTelemetry:
        enable: false
      gwAPIExperimentalFeatures:
        enable: false
      gatewayClassName: ngf
      replicas: 2
      affinity:
        podAntiAffinity:
          # setting to preferred instead of required so that scaling during updates can work correctly.
          # i only have 3 worker nodes, which means i can't have more than 3 pods total if i go the required route.
          # during an update, i may have more than 3 pods. going the preferred route solves this problem by loadbalancing as best as possible.
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - nginx-gateway-fabric
    nginx:
      replicas: 3
      service:
        externalTrafficPolicy: Cluster
      config:
        logging:
          agentLevel: info
          errorLevel: info
      debug: false
      pod:
        affinity:
          podAntiAffinity:
            # setting to preferred instead of required so that scaling during updates can work correctly.
            # i only have 3 worker nodes, which means i can't have more than 3 pods total if i go the required route.
            # during an update, i may have more than 3 pods. going the preferred route solves this problem by loadbalancing as best as possible.
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - nginx-gateway-fabric
