apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-account-adminpassword
  namespace: openbao
spec:
  refreshPolicy: CreatedOnce
  target:
    name: openbao-account-adminpassword
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        admin-password.txt: "{{ .password | toString }}" # password is the property in the generator output
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: openbao-account
