apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openbao-db
  namespace: openbao
spec:
  instances: 3
  certificates:
    serverCASecret: openbao-database-server-certificate
    serverTLSSecret: openbao-database-server-certificate
    clientCASecret: openbao-database-client-certificate
    replicationTLSSecret: openbao-database-client-certificate
  postgresql:
    pg_hba:
    - hostssl app all all cert
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: 5Gi
      storageClassName: no-replication
      volumeMode: Filesystem
  logLevel: info
