apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resources/certificate-openbao-server-tls.yaml
- resources/certificate-openbao-db-tls-replication.yaml
- resources/certificate-openbao-db-tls-server.yaml
